import type { User, Client, Centre, Activity } from "./types";

export const initialUsers: User[] = [
  {
    id: "u1",
    name: "Camille Roussel",
    initials: "CR",
    role: "Manager",
    team: "Déploiement",
    level: "Senior",
    availabilityByClient: { c1: "available", c2: "backup" },
  },
  {
    id: "u2",
    name: "Théo Lefèvre",
    initials: "TL",
    role: "OPS",
    team: "Déploiement",
    level: "Senior",
    availabilityByClient: { c1: "available", c2: "available" },
  },
  {
    id: "u3",
    name: "Inès Bouchard",
    initials: "IB",
    role: "OPS",
    team: "Déploiement",
    level: "Junior",
    availabilityByClient: { c1: "backup", c2: "available" },
  },
  {
    id: "u4",
    name: "Léa Morvan",
    initials: "LM",
    role: "OPS",
    team: "Déploiement",
    level: "Observateur",
    availabilityByClient: { c1: "available", c2: "unavailable" },
  },
  {
    id: "u5",
    name: "Mehdi Aït-Kaci",
    initials: "MA",
    role: "OPS",
    team: "Déploiement",
    level: "Junior",
    availabilityByClient: { c1: "available", c2: "available" },
  },
  {
    id: "u6",
    name: "Sarah Cohen",
    initials: "SC",
    role: "OPS",
    team: "Formation",
    level: "Senior",
    availabilityByClient: { c1: "unavailable", c2: "available" },
  },
  {
    id: "u7",
    name: "Julien Pasquier",
    initials: "JP",
    role: "OPS",
    team: "Déploiement",
    level: "Observateur",
    availabilityByClient: { c1: "available", c2: "backup" },
  },
  {
    id: "u8",
    name: "Noémie Tanguy",
    initials: "NT",
    role: "Logistique",
    team: "Déploiement",
    level: "Senior",
  },
  {
    id: "u9",
    name: "Adrien Vassard",
    initials: "AV",
    role: "OPS",
    team: "Formation",
    level: "Junior",
    availabilityByClient: { c1: "backup", c2: "available" },
  },
  {
    id: "u10",
    name: "Manon Bréhier",
    initials: "MB",
    role: "Admin",
    team: "Déploiement",
    level: "Senior",
  },
];

export const initialClients: Client[] = [
  {
    id: "c1",
    name: "PST 35",
    type: "SPSTI",
    dateDebut: "2026-04-06",
    dateFin: "2026-07-31",
    nbSalaries: 142,
  },
  {
    id: "c2",
    name: "AIST 84",
    type: "SPSTI",
    dateDebut: "2026-05-04",
    dateFin: "2026-09-12",
    nbSalaries: 89,
  },
];

export const initialCentres: Centre[] = [
  {
    id: "ce1",
    clientId: "c1",
    name: "Rennes Beaulieu",
    address: "12 av. de la Bouvardière, 35000 Rennes",
    isFormateur: true,
    nbSalaries: 38,
  },
  {
    id: "ce2",
    clientId: "c1",
    name: "Saint-Malo Centre",
    address: "4 rue du Port, 35400 Saint-Malo",
    isFormateur: false,
    nbSalaries: 22,
  },
  {
    id: "ce3",
    clientId: "c1",
    name: "Fougères Industrie",
    address: "ZA La Galaisière, 35300 Fougères",
    isFormateur: false,
    nbSalaries: 18,
  },
  {
    id: "ce4",
    clientId: "c2",
    name: "Avignon Cap-Sud",
    address: "rue Pierre Seghers, 84000 Avignon",
    isFormateur: true,
    nbSalaries: 31,
  },
  {
    id: "ce5",
    clientId: "c2",
    name: "Carpentras",
    address: "av. Jean Henri Fabre, 84200 Carpentras",
    isFormateur: false,
    nbSalaries: 27,
  },
];

export const initialActivities: Activity[] = [
  {
    id: "a1",
    type: "Accompagnement",
    subCategory: "PDS",
    clientId: "c1",
    centreId: "ce1",
    dateStart: "2026-05-18T09:00:00",
    dateEnd: "2026-05-18T17:30:00",
    assignees: ["u2", "u3", "u4"],
    status: "partial",
    validation: "prev",
    modality: "Présentiel",
  },
  {
    id: "a2",
    type: "Accompagnement",
    subCategory: "AM",
    clientId: "c1",
    centreId: "ce2",
    dateStart: "2026-05-19T09:00:00",
    dateEnd: "2026-05-19T17:30:00",
    assignees: [],
    status: "todo",
    validation: "prev",
    modality: "Présentiel",
  },
  {
    id: "a3",
    type: "Accompagnement",
    subCategory: "PDS",
    clientId: "c1",
    centreId: "ce3",
    dateStart: "2026-05-21T09:00:00",
    dateEnd: "2026-05-21T17:30:00",
    assignees: ["u5", "u3"],
    status: "done",
    validation: "validated",
    modality: "Présentiel",
  },
  {
    id: "a4",
    type: "Formation",
    subCategory: "PDS",
    clientId: "c1",
    centreId: "ce1",
    dateStart: "2026-05-15T09:00:00",
    dateEnd: "2026-05-15T17:00:00",
    assignees: ["u6"],
    status: "done",
    validation: "ready",
    modality: "Présentiel",
  },
  {
    id: "a5",
    type: "Accompagnement",
    subCategory: "IPRP",
    clientId: "c2",
    centreId: "ce4",
    dateStart: "2026-05-22T09:00:00",
    dateEnd: "2026-05-22T17:30:00",
    assignees: ["u2"],
    status: "partial",
    validation: "prev",
    modality: "Présentiel",
  },
  {
    id: "a6",
    type: "Accompagnement",
    subCategory: "AM",
    clientId: "c2",
    centreId: "ce5",
    dateStart: "2026-05-26T09:00:00",
    dateEnd: "2026-05-26T17:30:00",
    assignees: ["u5", "u9", "u4"],
    status: "alert",
    validation: "prev",
    modality: "Distanciel",
    cancelRequested: true,
  },
  {
    id: "a7",
    type: "Accompagnement",
    subCategory: "PDS",
    clientId: "c2",
    centreId: "ce4",
    dateStart: "2026-05-28T09:00:00",
    dateEnd: "2026-05-28T17:30:00",
    assignees: ["u3", "u5", "u9", "u7"],
    status: "done",
    validation: "validated",
    modality: "Présentiel",
  },
];

export const TICKET_TYPES = ["Idée", "Bug", "Question", "Amélioration"] as const;
export const TICKET_PRIORITIES = ["Faible", "Moyenne", "Haute", "Critique"] as const;
